FOSSC-70 python3-pyserial
Open-Source-Compliance/package-analysis pull request #100
Opened 2024-05-31 07:44 UTC by dierberg

2024-05-31 15:58 UTC, OliverFendt requested changes
@dierberg great contribution, I only have one small comment

2024-05-31 15:58 UTC, OliverFendt commented on analysed-packages/pyserial/version-3.5/pyserial-3.5-OSS-disclosure.txt
> +BSD-3-Clause
It is correct that the files of the package are licensed under BSD-3-Clause. The only thing which shall be corrected is the text of the BSD-3-Clause. It seems perhaps a little bit picky but you know we need to be as precise as possible. The text of the BSD-3-Clause license contained in the LICENSE.txt file in the root directory is:

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

\* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.

\* Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following
disclaimer in the documentation and/or other materials provided
with the distribution.

\* Neither the name of the copyright holder nor the names of its
contributors may be used to endorse or promote products derived
from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This license text contains "*" instead of "1.", "2.", "3." like the license text below. Please correct this. Please make sure that the file (/test/handlers/protocol_test.py) which has the license reference "this is distributed under a free software license, see license.txt" instead of "SPDX-License-Identifier: BSD-3-Clause" like all the others is also updated with the correct license text.

2024-05-31 15:58 UTC, OliverFendt commented on analysed-packages/pyserial/version-3.5/pyserial-3.5-SPDX2TV.spdx
Please see my comment on the disclosure document

2024-05-31 15:58 UTC, OliverFendt commented on analysed-packages/pyserial/version-3.5/pyserial-3.5.spdx.json
Please see my comment on the disclosure document

2024-05-31 15:58 UTC, OliverFendt commented on analysed-packages/pyserial/version-3.5/pyserial-3.5.spdx.rdf.xml
Please see my comment on the disclosure document

2024-05-31 15:58 UTC, OliverFendt commented on analysed-packages/pyserial/version-3.5/pyserial-3.5.spdx.yaml
Please see my comment on the disclosure document

2024-06-05 14:09 UTC, dierberg commented
BSD-3 fixed, documents updated.

2024-06-06 07:52 UTC, dierberg commented on analysed-packages/pyserial/version-3.5/pyserial-3.5-OSS-disclosure.txt
> +BSD-3-Clause
I think Fossology puts both variants to the spdx and README-OSS files. The one it has found (original BSD-3-Clause) and the version which we have concluded (from LICENSE.txt). Is that a new feature or bug in version 4.4.0?

2024-06-06 08:12 UTC, dierberg commented on analysed-packages/pyserial/version-3.5/pyserial-3.5-OSS-disclosure.txt
> +BSD-3-Clause
My fault, I have overseen one file with original BSD-3-Clause. Fixed

2024-06-06 14:47 UTC, OliverFendt approved these changes
Great, thank you very much for your effort @dierberg

2024-06-06 14:47 UTC, merged