FOSSC-86 jquery
Open-Source-Compliance/package-analysis pull request #114
Opened 2024-06-06 13:43 UTC by dierberg

2024-06-10 18:12 UTC, OliverFendt requested changes
Awesome work @dierberg , I only have some minor comments

2024-06-10 18:12 UTC, OliverFendt commented on analysed-packages/jquery/version-3.4.1/jquery-3.4.1-SPDX2TV.spdx
> +LicenseConcluded: LicenseRef-MIT AND LicenseRef-RequireJS
Why is there LicenseRef-MIT AND LicenseRef-RequireJS cocnluded as far as I can see there is only the statement 

> Released under MIT license, https://github.com/requirejs/requirejs/blob/master/LICENSE

this means in my opinion this file is licensed under MIT and you can find the license text at the given link - which you have than concluded to RequireJS, which is correct but the MIT conclusion is to much here

2024-06-10 18:12 UTC, OliverFendt commented on analysed-packages/jquery/version-3.4.1/jquery-3.4.1-OSS-disclosure.txt
> +warranty-disclaimer
Please see all my comments in the tag value file

2024-06-10 18:12 UTC, OliverFendt commented on analysed-packages/jquery/version-3.4.1/jquery-3.4.1-SPDX2TV.spdx
> +PackageCopyrightText: NOASSERTION
In the disclosure file you have listed the contributors but not here, why? can you please add them here too:

> PackageCopyrightText: <text> Authors ordered by first contribution. .... </text>

2024-06-10 18:12 UTC, OliverFendt commented on analysed-packages/jquery/version-3.4.1/jquery-3.4.1.spdx.json
Please resolve in this file my comments in the disclosure file and tag value file, too

2024-06-10 18:12 UTC, OliverFendt commented on analysed-packages/jquery/version-3.4.1/jquery-3.4.1.spdx.rdf.xml
Please resolve in this file my comments in the disclosure file and tag value file, too

2024-06-10 18:12 UTC, OliverFendt commented on analysed-packages/jquery/version-3.4.1/jquery-3.4.1.spdx.yaml
Please resolve in this file my comments in the disclosure file and tag value file, too

2024-06-11 08:10 UTC, dierberg commented
new documents generated

2024-06-11 12:32 UTC, OliverFendt approved these changes
Great, thank you very much for your effort

2024-06-11 12:33 UTC, merged