Preparing kbd/version-2.4.0/
Open-Source-Compliance/package-analysis pull request #117
Opened 2024-06-08 06:49 UTC by ParianGol

2024-06-22 18:01 UTC, OliverFendt requested changes
@ParianGol Excellent work.
Given the comment in the dbus curation I think the "warranty-disclaimer" conclusions ar based on your lawyers view.
Please resolve my comments, really very good work

2024-06-24 06:47 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/README.md
> +This package is dual licensed under MIT OR GPL-3.0-or-later. To facilitate automatic use, a default license choice of MIT is denoted in the Acknowledgment section of the OSS disclosure document. This
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/452d74cefb901cdb8f2d02a42c4e0d975b72914c
Done, thank you!

2024-06-24 07:14 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/kbd-2.4.0-SPDX2TV.spdx
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/aa6c58db9aa89c9bb7a032f869e9e1aa07a9dca2

2024-06-24 07:14 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/kbd-2.4.0.spdx.json
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/aa6c58db9aa89c9bb7a032f869e9e1aa07a9dca2

2024-06-24 07:14 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/kbd-2.4.0.spdx.rdf.xml
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/aa6c58db9aa89c9bb7a032f869e9e1aa07a9dca2

2024-06-24 07:14 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/kbd-2.4.0.spdx.yaml
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/aa6c58db9aa89c9bb7a032f869e9e1aa07a9dca2

2024-06-24 07:14 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/kbd-2.4.0-OSS-disclosure.txt
> +Copyright 1996-2006 Free Software Foundation, Inc.
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/aa6c58db9aa89c9bb7a032f869e9e1aa07a9dca2

2024-06-24 07:14 UTC, ParianGol commented on analysed-packages/kbd/version-2.4.0/kbd-2.4.0-SPDX2TV.spdx
> +FileChecksum: MD5: 25901bcde7fef71e773a7757757456
https://github.com/Open-Source-Compliance/package-analysis/pull/117/commits/aa6c58db9aa89c9bb7a032f869e9e1aa07a9dca2

2024-06-24 15:16 UTC, OliverFendt approved these changes
Excellent @ParianGol , thank you very much

2024-06-24 15:16 UTC, merged

2024-06-24 15:20 UTC, ParianGol commented
> @ParianGol Excellent work. Given the comment in the dbus curation I think the "warranty-disclaimer" conclusions ar based on your lawyers view. Please resolve my comments, really very good work

@OliverFendt Thank you very much! We will discuss with our lawyer to provide you a statement also for warranty-disclaimer.