FOSSC-88 alsa-utils
Open-Source-Compliance/package-analysis pull request #149
Opened 2024-08-29 09:57 UTC by dierberg

2024-09-02 18:43 UTC, OliverFendt requested changes
@dierberg  Awesome great work: I only have a few comments

2024-09-02 18:43 UTC, OliverFendt commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6-SPDX2TV.spdx
> +LicenseConcluded: LicenseRef-LGPL-2.0-or-later-c4a20a7c9332c01337a88843c850c213
E.g. here you have only the boilerplate of LGPL-2.0-or-later as license text conlude, please correct this. There might ba also other files with the wrong license text

2024-09-02 18:43 UTC, OliverFendt commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6-OSS-disclosure.txt
> +This configure script is free software; the Free Software Foundation gives
please add additionally:
This config.status script is free software; the Free Software Foundation
gives unlimited permission to copy, distribute and modify it.
See file "configure"

2024-09-02 18:43 UTC, OliverFendt commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6-SPDX2TV.spdx
Please resolve in this file my comments in the disclosure file too

2024-09-02 18:43 UTC, OliverFendt commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6.spdx.json
Please resolve in this file my comments in the disclosure file and tag value file, too

2024-09-02 18:43 UTC, OliverFendt commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6.spdx.rdf.xml
Please resolve in this file my comments in the disclosure file and tag value file, too

2024-09-02 18:43 UTC, OliverFendt commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6.spdx.yaml
Please resolve in this file my comments in the disclosure file and tag value file, too

2024-09-03 09:32 UTC, dierberg commented on analysed-packages/alsa-utils/version-1.2.6/alsa-utils-1.2.6-OSS-disclosure.txt
> +Copyright (c) by Jaroslav Kysela <perex@perex.cz> Based on vplay program by
Full copyright is: " ... Based on vplay programm by Michael Beck" I would like to have that reference (M.Beck is a former colleague of mine)

2024-09-03 17:42 UTC, OliverFendt approved these changes
Great work, thank you vrey much @dierberg

2024-09-03 17:42 UTC, merged